Vectorization is much faster than using explicit for loops

eg. computing z = w^T*x, where xeR^100000 and weR^100000

In [1]:
import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

start = time.time()
c = np.dot(a, b)
end = time.time()

print(f"c: {c}")
print(f"Vectorized: {1000*(end - start)}ms")

c = 0
start = time.time()
for i in range(1000000):
    c += a[i] * b[i]
end = time.time()

print(f"c: {c}")
print(f"For loop: {1000*(end - start)}ms")

c: 250455.59959064896
Vectorized: 1.0025501251220703ms
c: 250455.59959065064
For loop: 568.2260990142822ms


Broadcasting can also significantly speed up python code

In [2]:
# Broadcasting eg.
# Divide each entry in column by sum of entries in that column

A = np.array([[1, 2, 3, 11],
              [4, 5, 6, 12],
              [7, 8, 9, 13]])
print(A)

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

In [3]:
col_sum = A.sum(axis=0) # axis = 0 denotes vertical sum
print(col_sum)

[12 15 18 36]


In [4]:
div = A/col_sum.reshape(1, 4) # Reshape col_sum to a 1x4 matrix divide matrix A by it
print(div)

[[0.08333333 0.13333333 0.16666667 0.30555556]
 [0.33333333 0.33333333 0.33333333 0.33333333]
 [0.58333333 0.53333333 0.5        0.36111111]]


Extra python-numpy vector notes

In [10]:
# Better to specify both rows and columns when initializing a vector
bad = np.random.randn(5) # bad; only specified cols
print("This is bad:")
print(bad)
print(f"Transpose: {bad.T}\n")

good = np.random.randn(5, 1) # good; specified that its a 5x1 column matrix
print("This is good:")
print(good)
print(f"Transpose: {good.T}")

This is bad:
[ 0.97601153  0.61111749 -0.27121165 -0.65104352 -0.54773022]
Transpose: [ 0.97601153  0.61111749 -0.27121165 -0.65104352 -0.54773022]

This is good:
[[ 1.79779231]
 [ 0.913771  ]
 [-0.84095159]
 [-1.43963672]
 [ 0.27589339]]
Transpose: [[ 1.79779231  0.913771   -0.84095159 -1.43963672  0.27589339]]
