In [1]:
import numpy as np

a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c.shape)

(2, 3)


In [7]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [8]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [12]:
# a.shape = (3,4)# b.shape = (4,1)
a = np.random.randn(3, 4) # a.shape = (4, 3)
b = np.random.randn(4, 1)
c = np.random.randn(3, 4)
for i in range(3): 
    for j in range(4): 
        c[i][j] = a[i][j] + b[j]
print(f"c:\n {c}")
print(f"vec:\n {a + b.T}")

c:
 [[-1.03375981  1.51857122  1.15098194  0.76875385]
 [-2.06581819  0.47401899  2.02146539  0.89479951]
 [-1.01311308  0.81186692  1.64287581  0.93402726]]
vec:
 [[-1.03375981  1.51857122  1.15098194  0.76875385]
 [-2.06581819  0.47401899  2.02146539  0.89479951]
 [-1.01311308  0.81186692  1.64287581  0.93402726]]


In [16]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c.shape)

(3, 3)
